version: 2

models:

  - name: dim_channels
    columns:
      - name: channel_key
        tests:
          - unique
          - not_null

  - name: dim_dates
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
  - name: fct_image_detections

    columns:

      - name: message_id

        tests:
          - not_null  - name: image_category

        tests:
          - not_null